### ISSUE TITLE
Streamer mode

### ISSUE THREAD

**Issue by superRandomGuy941** [Mark7888/steelseries-sonar-py#1]
Hi,
I like to use sonar in streamer mode, which is not supported here.
I already found out the url being http://127.0.0.1:SOME_PORT/volumeSettings/streamer/.
This website show the following output:
`{"masters":{"stream":{"streaming":{"volume":1.0,"muted":false},"monitoring":{"volume":1.0,"muted":false}},"classic":{"volume":0.0,"muted":false}},"devices":{"game":{"stream":{"streaming":{"volume":1.0,"muted":false},"monitoring":{"volume":0.75,"muted":false}},"classic":{"volume":0.0,"muted":false}},"chatRender":{"stream":{"streaming":{"volume":0.5,"muted":false},"monitoring":{"volume":1.0,"muted":false}},"classic":{"volume":0.0,"muted":false}},"chatCapture":{"stream":{"streaming":{"volume":1.0,"muted":false},"monitoring":{"volume":1.0,"muted":false}},"classic":{"volume":0.0,"muted":false}},"media":{"stream":{"streaming":{"volume":0.5,"muted":false},"monitoring":{"volume":0.76,"muted":false}},"classic":{"volume":0.0,"muted":false}},"aux":{"stream":{"streaming":{"volume":0.5,"muted":false},"monitoring":{"volume":1.0,"muted":false}},"classic":{"volume":0.0,"muted":false}}}}`

I tried multiple versions of the `{self.web_server_address}/volumeSettings/streamer/{channel}/Volume/{json.dumps(volume)}` command  however nothing will happen. Also I don't know how to do that wireshark thing.

I tried setting the json value from the 'volumeSettings/streamer' page with this command `json_text['devices']['game']['stream']['monitoring']['volume'] = volume` as well which again does not do a thing.

Is there any possiblity to do that?

**Comment by superRandomGuy941** [comment]
Accidentally solved this issue this url will be required to change the setting i wanted to change `{self.web_server_address}/volumeSettings/streamer/monitoring/{channel}/Volume/{json.dumps(volume)}`

**Comment by Mark7888** [comment]
Thanks a lot for figuring out, how the streamer mode works. I have implemented it, and published the package on [PyPI](https://pypi.org/project/steelseries-sonar-py/).
