### ISSUE TITLE
Streaming mode not working

### ISSUE THREAD

**Issue by Mark7888** [Mark7888/steelseries-sonar-py#4]
It seems like the api endpoint for streaming mode volume control doesn't work for some reason. I have to investigate this further more, just took a look at it yesterday, and I got 404 status code as response

**Comment by raphael069** [comment]
It looks like the streamer mode urls changed, and look like this now    
`.../volumeSettings/streamer/streaming/master/volume/[volume value]`

**Comment by Mark7888** [comment]
Thanks, will take a look at it

**Comment by Mark7888** [comment]
Okay, i figured it out. I don't use streamer mode myself, but tested it a bit. Streamer mode gives 2 sliders for each channel: `streaming` and `monitoring`.

![image](https://github.com/Mark7888/steelseries-sonar-py/assets/44124704/44f32e83-a1c2-4a50-bfbd-3c89b15c144a)

Left one with the headphone icon is `monitoring`, and the right one is the `streaming` one.
I just have to make a way to adjust each one separately.

But to get the current volume data, I have to use the base url of `.../volumeSettings/streamer`.

**Comment by Mark7888** [comment]
I'm thinking if it is possible to even toggle streamer mode through the api 🤔

**Comment by Mark7888** [comment]
Resolved #8
